group("SourceSDK")
	project("raytrace")
		kind("StaticLib")
		warnings("Default")
		location("../projects/" .. os.target() .. "/" .. _ACTION)
		targetdir("%{prj.location}/%{cfg.architecture}/%{cfg.buildcfg}")
		debugdir("%{prj.location}/%{cfg.architecture}/%{cfg.buildcfg}")
		objdir("!%{prj.location}/%{cfg.architecture}/%{cfg.buildcfg}/intermediate/%{prj.name}")
		externalincludedirs({"../utils/common", "../public", "../public/tier0", "../public/tier1"})
		files({"raytrace.cpp", "trace2.cpp","trace3.cpp"})
		vpaths({["Source files/*"] = "*.cpp"})

		IncludeSDKCommonInternal()
