group("SourceSDK")
	project("mathlib")
		kind("StaticLib")
		warnings("Default")
		location("../projects/" .. os.target() .. "/" .. _ACTION)
		defines("MATHLIB_LIB")
		targetdir("%{prj.location}/%{cfg.architecture}/%{cfg.buildcfg}")
		debugdir("%{prj.location}/%{cfg.architecture}/%{cfg.buildcfg}")
		objdir("!%{prj.location}/%{cfg.architecture}/%{cfg.buildcfg}/intermediate/%{prj.name}")
		externalincludedirs({"../public", "../public/mathlib", "../public/tier0"})
		files({
			"expressioncalculator.cpp",
			"color_conversion.cpp",
			"cholesky.cpp",
			"halton.cpp",
			"lightdesc.cpp",
			"mathlib_base.cpp",
			"powsse.cpp",
			"sparse_convolution_noise.cpp",
			"sseconst.cpp",
			"sse.cpp",
			"ssenoise.cpp",
			"anorms.cpp",
			"bumpvects.cpp",
			"IceKey.cpp",
			"kdop.cpp",
			"imagequant.cpp",
			"spherical.cpp",
			"polyhedron.cpp",
			"quantize.cpp",
			"randsse.cpp",
			"simdvectormatrix.cpp",
			"vmatrix.cpp",
			"almostequal.cpp",
			"simplex.cpp",
			"eigen.cpp",
			"box_buoyancy.cpp",
			"camera.cpp",
			"planefit.cpp",
			"polygon.cpp",
			"volumeculler.cpp",
			"transform.cpp",
			"sphere.cpp",
			"capsule.cpp",
			"noisedata.h",
			"sse.h",
			"../public/mathlib/anorms.h",
			"../public/mathlib/bumpvects.h",
			"../public/mathlib/beziercurve.h",
			"../public/mathlib/camera.h",
			"../public/mathlib/compressed_3d_unitvec.h",
			"../public/mathlib/compressed_light_cube.h",
			"../public/mathlib/compressed_vector.h",
			"../public/mathlib/expressioncalculator.h",
			"../public/mathlib/halton.h",
			"../public/mathlib/IceKey.H",
			"../public/mathlib/lightdesc.h",
			"../public/mathlib/math_pfns.h",
			"../public/mathlib/mathlib.h",
			"../public/mathlib/noise.h",
			"../public/mathlib/polyhedron.h",
			"../public/mathlib/quantize.h",
			"../public/mathlib/simdvectormatrix.h",
			"../public/mathlib/spherical_geometry.h",
			"../public/mathlib/ssemath.h",
			"../public/mathlib/ssequaternion.h",
			"../public/mathlib/vector.h",
			"../public/mathlib/vector2d.h",
			"../public/mathlib/vector4d.h",
			"../public/mathlib/vmatrix.h",
			"../public/mathlib/vplane.h",
			"../public/mathlib/simplex.h",
			"../public/mathlib/eigen.h",
			"../public/mathlib/box_buoyancy.h",
			"../public/mathlib/cholesky.h",
			"../public/mathlib/planefit.h",
			"../public/mathlib/intvector3d.h",
			"../public/mathlib/polygon.h",
			"../public/mathlib/quadric.h",
			"../public/mathlib/volumeculler.h",
			"../public/mathlib/transform.h",
			"../public/mathlib/sphere.h",
			"../public/mathlib/capsule.h"
		})
		vpaths({
			["Source files/*"] = "*.cpp",
			["Header files/*"] = {"*.h", "../public/mathlib/*.h"}
		})

		IncludeSDKCommonInternal()

		filter("system:linux")
			disablewarnings("ignored-attributes")
